import pyperclip


class Credential:
    users_list = []

    def __init__(self, identity, user_name, password):

        self.identity = identity
        self.user_name = user_name
        self_password = password

    def save_credential(self):
        Credential.user_list.append(self)

    @classmethod
    def authenticate_user(cls, user_name, key):
        '''
        Method that checks if the username and password are correct
        '''
        for user in cls.users_list:
            if user.user_name == user_name and user.password == key:
                # print(user.identity)
                return user
        return 0


class UsersData:
    '''
    Class that holds website and password data for the users
    '''
    data_list = []

    def __init__(self, identity, data_id, website, web_key):
        self.identity = identity
        self.data_id = data_id
        self.website = website
        self.web_key = web_key

    def add_password(self):
        '''
        creating a method that creates the username and password
        '''
        UsersData.data_list.append(self)

    @classmethod
    def display_data(cls, number, count):
        '''
        display all passwords generated by the user
        '''
        for password in cls.data_list:
            if password.identity == number:
                if password.data_id == count:
                    return password

    @classmethod
    def existing_data(cls, number):
        '''
        Checks if data exists in the profile
        '''
        for data in cls.data_list:
            if data.identity == number:
                return True
        return False

    @classmethod
    def copy_password(cls, number, count):
        found_password = UsersData.display_data(number, count)
        pyperclip.copy(found_password.web_key)
